return {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
        local harpoon = require("harpoon")
        harpoon:setup()
        vim.keymap.set("n", "<Leader>hd", function()
            harpoon:list():clear()
        end, { desc = "Clear all bookmarks" })
        vim.keymap.set("n", "<Leader>hh", function()
            harpoon.ui:toggle_quick_menu(harpoon:list())
        end, { desc = "Clear all bookmarks" })
        vim.keymap.set("n", "<Leader>ha", function()
            harpoon:list():add()
        end)
        vim.keymap.set("n", "[h", function()
            harpoon:list():prev()
        end)
        vim.keymap.set("n", "]h", function()
            harpoon:list():next()
        end)
        vim.keymap.set("n", "<Leader>1", function()
            harpoon:list():select(1)
        end)
        vim.keymap.set("n", "<Leader>2", function()
            harpoon:list():select(2)
        end)
        vim.keymap.set("n", "<Leader>2", function()
            harpoon:list():select(3)
        end)
        vim.keymap.set("n", "<Leader>4", function()
            harpoon:list():select(4)
        end)
        vim.keymap.set("n", "<Leader>5", function()
            harpoon:list():select(5)
        end)
    end,
}
