require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.keymaps"

require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.project"
require "user.indentline"

require "user.autocmds"
